services:
  - type: web
    name: text-summarizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FIREBASE_API_KEY
        value: AIzaSyBqHUAA54OOSIt2RnjvDy2dgfBHgyADNmY
      - key: FIREBASE_AUTH_DOMAIN
        value: datasummarizationlogin.firebaseapp.com
      - key: FIREBASE_PROJECT_ID
        value: datasummarizationlogin
      - key: FIREBASE_STORAGE_BUCKET
        value: datasummarizationlogin.firebasestorage.app
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: "868563886977"
      - key: FIREBASE_APP_ID
        value: "1:868563886977:web:6313171684effe64173e80"
      - key: SECRET_KEY
        sync: false
      - key: PORT
        value: "10000" 